networks:
  default:
  website:

services:
  speakarr-santarr:
    build: .
    env_file:
      - stack.env
    networks:
      - default
      - website
    volumes:
      - ${CONFIG_DIR}:/config
      - ${EXTRA_VOLUMES}
    extra_hosts:
      - "api.bookinfo.club:127.0.0.1"
      - "www.goodreads.com:127.0.0.1"
    restart: unless-stopped
