networks:
  default:
  website:
  multimedia_prowlarr_santarr_speakarr:
    external: true
  multimedia_deluge_santarr_speakarr:
    external: true
  multimedia_sabnzbd_santarr_speakarr:
    external: true

services:
  speakarr-santarr:
    build: .
    env_file:
      - stack.env
    networks:
      - default
      - website
      - multimedia_prowlarr_santarr_speakarr
      - multimedia_deluge_santarr_speakarr
      - multimedia_sabnzbd_santarr_speakarr
    volumes:
      - ${CONFIG_DIR}:/config
      - ${EXTRA_VOLUMES}
    extra_hosts:
      - "api.bookinfo.club:127.0.0.1"
      - "www.goodreads.com:127.0.0.1"
    restart: unless-stopped
